# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'errorlet'
description: 'a simple custom error library'
version: '0.1.0'
repository:
  type: 'git'
  url: 'git://github.com/yinso/errorlet.git'
main: './lib/'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
devDependencies:
  coffee-script: =1.8.0
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.3.0'
